<a href="https://colab.research.google.com/github/Omoadonibetty/Machine-Learning-on-Titanic-Dataset/blob/main/titanic_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
titanic = pd.read_csv('/content/titanic.csv')
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titan = titanic.drop(['Name', 'PassengerId','Ticket', 'Cabin', 'Embarked', 'SibSp', 'Parch'], axis = "columns")
titan

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [ ]:
titan.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [ ]:
titan['Age'].median()

28.0

In [ ]:
fill_titan = titan['Age'].fillna(28, inplace = True)
fill_titan

In [ ]:
dependent = titan["Survived"]
dependent

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
independent = titan.drop(['Survived'], axis = 'columns')
independent

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female  28.0  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [ ]:
le_sex = LabelEncoder()
le_sex

LabelEncoder()

In [ ]:
independent['le_sex_n'] = le_sex.fit_transform(independent['Sex'])
independent['le_sex_n']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: le_sex_n, Length: 891, dtype: int64

In [ ]:
independent

Pclass     Sex   Age     Fare  le_sex_n
0         3    male  22.0   7.2500         1
1         1  female  38.0  71.2833         0
2         3  female  26.0   7.9250         0
3         1  female  35.0  53.1000         0
4         3    male  35.0   8.0500         1
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         1
887       1  female  19.0  30.0000         0
888       3  female  28.0  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         1

[891 rows x 5 columns]

In [ ]:
real_independent = independent.drop(["Sex"], axis = 'columns')
real_independent

Pclass   Age     Fare  le_sex_n
0         3  22.0   7.2500         1
1         1  38.0  71.2833         0
2         3  26.0   7.9250         0
3         1  35.0  53.1000         0
4         3  35.0   8.0500         1
..      ...   ...      ...       ...
886       2  27.0  13.0000         1
887       1  19.0  30.0000         0
888       3  28.0  23.4500         0
889       1  26.0  30.0000         1
890       3  32.0   7.7500         1

[891 rows x 4 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(real_independent, dependent, test_size= 0.2)
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

712
179
712
179


In [ ]:
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [ ]:
model.fit(real_independent, dependent)

DecisionTreeClassifier()

In [ ]:
model.score(real_independent, dependent)

0.9775533108866442

In [ ]:
model.predict([[1,50,10,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
model.predict([[3,25,1000,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
model.predict([[2,80,100,1,]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
real_independent

Pclass   Age     Fare  le_sex_n
0         3  22.0   7.2500         1
1         1  38.0  71.2833         0
2         3  26.0   7.9250         0
3         1  35.0  53.1000         0
4         3  35.0   8.0500         1
..      ...   ...      ...       ...
886       2  27.0  13.0000         1
887       1  19.0  30.0000         0
888       3  28.0  23.4500         0
889       1  26.0  30.0000         1
890       3  32.0   7.7500         1

[891 rows x 4 columns]